require('dotenv').config();
const crypto = require('crypto');

function requireEnv(name) {
  const value = String(process.env[name] || '').trim();
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function firstEnvironmentValue(names) {
  for (const name of names) {
    const value = String(process.env[name] || '').trim();
    if (value) return value;
  }
  return '';
}

function resolveDatabaseUrl() {
  const direct = firstEnvironmentValue([
    'DATABASE_URL',
    'DATABASE_PRIVATE_URL',
    'POSTGRES_URL',
    'POSTGRES_URL_NON_POOLING',
    'DATABASE_PUBLIC_URL'
  ]);
  if (direct) return direct;

  // Railway can expose PostgreSQL as separate PG* variables when a URL
  // reference was not copied to the bot service. Rebuild the same connection
  // URL without logging any credential.
  const host = String(process.env.PGHOST || '').trim();
  const port = String(process.env.PGPORT || '5432').trim();
  const user = String(process.env.PGUSER || '').trim();
  const password = String(process.env.PGPASSWORD || '').trim();
  const database = String(process.env.PGDATABASE || '').trim();
  if (host && user && database) {
    const auth = password
      ? `${encodeURIComponent(user)}:${encodeURIComponent(password)}`
      : encodeURIComponent(user);
    return `postgresql://${auth}@${host}:${port}/${encodeURIComponent(database)}`;
  }

  throw new Error(
    'DATABASE_URL is required. Railway: add DATABASE_URL=${{Postgres.DATABASE_URL}} '
    + "to this bot service's Variables (replace Postgres if your database service has another name)."
  );
}

function parseAdminIds() {
  const raw = process.env.ADMIN_IDS || process.env.ADMIN_ID || '';
  const ids = raw
    .split(',')
    .map(value => Number(String(value).trim()))
    .filter(Number.isFinite);
  if (!ids.length) throw new Error('ADMIN_IDS or ADMIN_ID is required');
  return new Set(ids);
}

const adminIds = parseAdminIds();
const virtualNumberCostViewerIds = (() => {
  const explicit = String(process.env.VIRTUAL_NUMBERS_COST_VIEWER_IDS || process.env.VIRTUAL_NUMBERS_COST_VIEWER_ID || '').trim();
  if (explicit) {
    return new Set(explicit.split(',').map(value => Number(String(value).trim())).filter(Number.isFinite));
  }
  // By default only the first/main admin can see provider acquisition costs.
  const firstAdmin = [...adminIds][0];
  return new Set(Number.isFinite(firstAdmin) ? [firstAdmin] : []);
})();

const token = requireEnv('BOT_TOKEN');
const databaseUrl = resolveDatabaseUrl();
const databaseSchemaRaw = String(process.env.DATABASE_SCHEMA || 'public').trim();
if (!/^[A-Za-z_][A-Za-z0-9_]{0,62}$/.test(databaseSchemaRaw)) {
  throw new Error('DATABASE_SCHEMA must start with a letter/underscore and contain only letters, numbers, or underscores');
}
const databaseSchema = databaseSchemaRaw;
const networkRole = ['master', 'client', 'standalone'].includes(String(process.env.NETWORK_ROLE || '').toLowerCase())
  ? String(process.env.NETWORK_ROLE).toLowerCase()
  : 'master';
if (networkRole === 'client' && !String(process.env.DATABASE_SCHEMA || '').trim()) {
  console.warn('DATABASE_SCHEMA is missing for a client bot; set the separate client_* schema generated by the master bot.');
}
const configuredInventoryKey = String(process.env.INVENTORY_ENCRYPTION_KEY || '').trim();
let inventoryKey = configuredInventoryKey;
if (inventoryKey && !/^[0-9a-fA-F]{64}$/.test(inventoryKey)) {
  throw new Error('INVENTORY_ENCRYPTION_KEY must be exactly 64 hexadecimal characters');
}
if (!inventoryKey) {
  // Backward-compatible fallback for the old single-file bot, which did not
  // have an inventory encryption environment variable. Keep BOT_TOKEN stable
  // or, preferably, set INVENTORY_ENCRYPTION_KEY explicitly in Railway.
  inventoryKey = crypto.createHash('sha256').update(`cd-store-inventory-v1:${token}`).digest('hex');
  console.warn('INVENTORY_ENCRYPTION_KEY is missing; using a BOT_TOKEN-derived compatibility key.');
}

module.exports = {
  token,
  databaseUrl,
  databaseSchema,
  admins: adminIds,
  port: Number(process.env.PORT || 3000),
  railway: {
    // Used only when generating the ready-to-paste Variables block for a new
    // partner bot. The user's Railway project names its database service this
    // way; it can still be overridden once on the master bot if renamed.
    databaseServiceName: String(
      process.env.RAILWAY_DATABASE_SERVICE_NAME || 'Postgres قاعدة البيانات'
    ).trim()
  },
  supportUsername: String(process.env.SUPPORT_USERNAME || '').replace(/^@/, ''),
  defaultLanguage: process.env.DEFAULT_LANGUAGE === 'en' ? 'en' : 'ar',
  captchaEnabled: process.env.CAPTCHA_ENABLED !== 'false',
  inventoryKey,
  superQiNumber: String(process.env.SUPERQI_NUMBER || '917392710336').trim(),
  iqdRate: Number(process.env.IQD_RATE || 1500),

  network: {
    role: networkRole,
    apiUrl: (() => {
      const raw = String(process.env.NETWORK_API_URL || '').trim().replace(/\/$/, '');
      if (!raw) return '';
      return /^https?:\/\//i.test(raw) ? raw : `https://${raw}`;
    })(),
    publicUrl: (() => {
      const raw = String(process.env.NETWORK_PUBLIC_URL || (process.env.RAILWAY_PUBLIC_DOMAIN ? `https://${process.env.RAILWAY_PUBLIC_DOMAIN}` : '')).trim().replace(/\/$/, '');
      if (!raw) return '';
      return /^https?:\/\//i.test(raw) ? raw : `https://${raw}`;
    })(),
    apiKey: String(process.env.NETWORK_API_KEY || '').trim(),
    shopId: String(process.env.NETWORK_SHOP_ID || '').trim() || `shop-${[...adminIds][0]}`,
    shopName: String(process.env.NETWORK_SHOP_NAME || 'متجري').trim(),
    ownerName: String(process.env.NETWORK_OWNER_NAME || 'نبيل').trim(),
    settlementCurrency: ['IQD', 'EGP', 'USD'].includes(String(process.env.NETWORK_SETTLEMENT_CURRENCY || '').toUpperCase())
      ? String(process.env.NETWORK_SETTLEMENT_CURRENCY).toUpperCase()
      : 'USD',
    egpRate: Number(process.env.EGP_RATE_PER_USD || 50),
    iqdRate: Number(process.env.IQD_RATE || 1500),
    sellerCommissionPercent: Math.min(50, Math.max(0, Number(process.env.NETWORK_SELLER_COMMISSION_PERCENT || 10))),
    debtReminderMinutes: Math.max(5, Number(process.env.NETWORK_DEBT_REMINDER_MINUTES || 30)),
    debtReminderThresholdUsd: Math.max(0, Number(process.env.NETWORK_DEBT_REMINDER_THRESHOLD_USD || 15)),
    debtSuspendThresholdUsd: Math.max(1, Number(process.env.NETWORK_DEBT_SUSPEND_THRESHOLD_USD || 40))
  },
  virtualNumbers: {
    enabled: String(process.env.VIRTUAL_NUMBERS_ENABLED || 'true').toLowerCase() !== 'false',
    apiKey: String(process.env.SMSBOWER_API_KEY || process.env.VIRTUAL_NUMBERS_API_KEY || '').trim(),
    baseUrl: String(process.env.SMSBOWER_BASE_URL || process.env.VIRTUAL_NUMBERS_BASE_URL || 'https://smsbower.page/stubs/handler_api.php').trim(),
    smsBowerWalletUrl: String(process.env.SMSBOWER_WALLET_URL || 'https://smsbower.page/api/payment/getActualWalletAddress').trim(),
    smsmanApiKey: String(process.env.SMSMAN_API_KEY || '').trim(),
    smsmanBaseUrl: String(process.env.SMSMAN_BASE_URL || 'https://api.sms-man.com/stubs/handler_api.php').trim(),
    grizzlyApiKey: String(process.env.GRIZZLYSMS_API_KEY || '').trim(),
    grizzlyBaseUrl: String(process.env.GRIZZLYSMS_BASE_URL || 'https://api.grizzlysms.com/stubs/handler_api.php').trim(),
    timeoutMs: Math.min(30000, Math.max(3000, Number(process.env.VIRTUAL_NUMBERS_TIMEOUT_MS || 12000))),
    pollIntervalMs: Math.max(5000, Number(process.env.VIRTUAL_NUMBERS_POLL_INTERVAL_MS || 7000)),
    // Virtual numbers are auto-cancelled after exactly 10 minutes if no SMS code arrives.
    activationTimeoutMinutes: 10,
    costViewerIds: virtualNumberCostViewerIds
  },
  binance: {
    // Normal Binance account API keys with read permission only.
    // Legacy BINANCE_PAY_* names are accepted so the current Railway setup keeps working.
    apiKey: String(process.env.BINANCE_API_KEY || process.env.BINANCE_PAY_API_KEY || '').trim(),
    secretKey: String(
      process.env.BINANCE_API_SECRET ||
      process.env.BINANCE_SECRET_KEY ||
      process.env.BINANCE_PAY_SECRET_KEY ||
      ''
    ).trim(),
    payId: String(process.env.BINANCE_PAY_ID || process.env.BINANCE_ID || '').trim(),
    baseUrl: String(process.env.BINANCE_API_BASE_URL || 'https://api.binance.com').replace(/\/$/, ''),
    minAmount: 0.01,
    maxAmount: Math.max(1, Number(process.env.BINANCE_MAX_AMOUNT || 100000)),
    verificationWindowHours: Math.min(24, Math.max(1, Number(process.env.BINANCE_VERIFY_WINDOW_HOURS || 6)))
  }
};
